apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microshak_web_UI
  namespace: argocd
spec:
  project: microshak

  source:
    repoURL: https://gitlab.com/nanuchi/argocd-app-config.git
    targetRevision: HEAD
    path: Microshak
  destination: 
    server: https://kubernetes.default.svc
    namespace: microshak

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

