apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microshak.web.ui
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Microshak/argo.git
    targetRevision: HEAD
    path: microshak
  destination: 
    server: https://kubernetes.default.svc
    namespace: microshak

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

