apiVersion: apps/v1
kind: Deployment
metadata:
  name: cool-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cool-app
  template:
    metadata:
      labels:
        app: cool-app
        label-key : cool-app-key
    spec:
      containers:
        - name: cool-app-container
          image: microshak/indexeddb:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 80