apiVersion: apps/v1
kind: Deployment
metadata:
  name: microshak-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microshak-service
  template:
    metadata:
      labels:
        app: microshak-service
    spec:
      containers:
      - name: microshak-service
        image: microshak/indexeddb:latest
        ports:
        - containerPort: 80