apiVersion: apps/v1
kind: Deployment
metadata:
  name: microshak-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microshak-webserver
  template:
    metadata:
      labels:
        app: microshak-webserver
    spec:
      containers:
      - name: microshak-webserver
        image: microshak/indexeddb:latest
        ports:
        - containerPort: 80