apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: microshak-gateway
  namespace: microshak
spec:
  selector:
    app: microshak-gateway-controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - microshak.com
    - www.microshak.com
