apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: istio
  name: ingress
spec:
  rules:
  - host: microshak.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: microshak
            port:
              number: 80