apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: microshak-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "microshak-service.default.svc.cluster.local"
    - "microshak.com"


