apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: microshak-gateway
  namespace: microshak
spec:
  selector:
    app: microshak
  servers:
    -port: 
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - microshak.com
tls:
      httpsRedirect: false

---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: microshak-route
  namespace: microshak
spec:
  gateways:
  - microshak/microshak-gateway
  hosts:
  - microshak.com
  http:
  - route:
    - destination:
        host: microshak.microshak.svc.cluster.local