apiVersion: v1
kind: Service
metadata:
  labels:
    app: microshak
  name: webserver
  namespace: microshak
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: webserver
  type: ClusterIP