apiVersion: v1
kind: Service
metadata:
  name: microservice
  labels:
    app: microservice
    service: microservice
spec:
  selector:
    app: microshak-web
  ports:
  - name: http
    port: 80
  type: LoadBalancer
